import { ApiBoard, Board } from "@/types/board.types";
import { ApiPictogram, Pictogram } from "@/types/pictogram.types";
import Constants from "expo-constants";

const API_BASE_URL =
  (Constants.expoConfig?.extra?.API_BASE_URL as string) ?? "";

/**
 * Receives the URL generated by the backend (which may contain 'localhost')
 * and replaces the domain with the actual IP configured in the app's .env file.
 * This ensures that the mobile phone can access the files even if
 * the backend uses 'localhost' as the base URL.
 */
function resolveFileUrl(fileUrl: string): string {
  if (!fileUrl || !API_BASE_URL) return fileUrl;

  try {
    const parsed = new URL(fileUrl);
    const base = new URL(API_BASE_URL);
    // Only the protocol and host are changed, the path (/files/uuid) remains the same.
    return `${base.protocol}//${base.host}${parsed.pathname}`;
  } catch {
    return fileUrl;
  }
}

export const boardAdapter = {
  toPictogram(apiData: ApiPictogram): Pictogram {
    return {
      id: apiData.id,
      uuid: apiData.uuid,
      description: apiData.description,
      imageSource: resolveFileUrl(apiData.fileUrl),
      createdAt: apiData.createdAt,
      updatedAt: apiData.updatedAt,
    };
  },

  toBoard(apiData: ApiBoard): Board {
    return {
      id: apiData.id,
      uuid: apiData.uuid,
      title: apiData.title,
      representativePictogram: this.toPictogram(
        apiData.representativePictogram,
      ),
      pictogramCount: apiData.pictogramCount,
      createdAt: apiData.createdAt,
      updatedAt: apiData.updatedAt,
    };
  },
};
